schematic: ./tb_dc.sch
template: ./tb_dc.spice.j2
filename_raw: results.raw
filename_log: op.log
parameters:
  vdda: 3.3
  vin_dc: 1.5
  i_bias: 5e-05
  corner: typical

plot_specs:
  dc_tf: ./plots/dc_tf.yaml



